root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/serial-app ."
bin = "./tmp/serial-app"
include_ext = ["go"]
exclude_dir = ["tmp"]
delay = 1000
kill_delay = 500
# For windows
poll=true

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"